name: Build APK file
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: build with buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          # workdir: .  # default
          # buildozer_version: stable  # default

      - name: upload artifacts to github
        uses: actions/upload-artifact@v2
        with:
          name: life_pod
          path: ${{ steps.buildozer.outputs.filename }}
